### ISSUE TITLE
Paquetes (crackmapexec,enum4linux) inexistente en los repositorios de Ubuntu

### ISSUE THREAD

**Issue by kaelthasmanu** [XDeadHackerX/NetRadar#2]
Probando esta interesante herramienta me encontre con que los siguientes paquetes no existian en mis repositorios :
![Screenshot from 2023-08-16 00-04-57](https://github.com/XDeadHackerX/NetRadar/assets/39976595/0408a9dc-1bff-4378-82e0-9003963146f0)

Buscando un poco mas de informacion los paquetes existen en los repositorios de Kali Linux:
![Screenshot from 2023-08-16 00-05-42](https://github.com/XDeadHackerX/NetRadar/assets/39976595/916df393-0917-4c45-b802-abdf87b57ab7)

El error esta erreglado en el PR -> [Fixed](https://github.com/XDeadHackerX/NetRadar/pull/1)

**Comment by XDeadHackerX** [comment]
Gracias por el aporte, desafortunadamente la herramienta no esta preparada para trabajar en Ubuntu.
